### PR TITLE
YUNIKORN-1390 - MPI Operator Example in k8-shim repo

### PR DESCRIPTION
**Pull request by kannon92**
### What is this PR for?

In my researching Yunikorn, I wanted to see if its possible to use MPIJob from Kubeflow with Yunikorn.  

I added an example from the Kubeflow examples and adding some yunikorn annotations.  

This PR adds an example to the deployment/examples repo to show how you could use yunikorn and MPIJob.

### What type of PR is it?
* [ ] - Bug Fix
* [ ] - Improvement
* [ ] - Feature
* [x] - Documentation
* [ ] - Hot Fix
* [ ] - Refactoring

### Todos
* [ ] - Task

### What is the Jira issue?
* Open an issue on Jira https://issues.apache.org/jira/browse/YUNIKORN/
* Put link here, and add [YUNIKORN-*Jira number*] in PR title, eg. `[YUNIKORN-2] Gang scheduling interface parameters`

### How should this be tested?

1) Clone Kubeflow mpijob repo.
2) Deploy v2beta controller
3) Run the pi.yaml job
4) Use the UI to view that yunikorn correctly reports the MPIJob

### Questions:
* [ ] - The licenses files need update.
* [ ] - There is breaking changes for older versions.
* [ ] - It needs documentation.

### CODE REVIEW

**Comment by wilfred-s** [comment]
Hi @kannon92 can you check the pre-commit run please? I think it is purely due to the fact that the files must have a proper header which is missing.
Beside that I do not think anything is stopping us from adding this to the repo.

**Review by 0yukali0 — COMMENTED** [review]
LGTM.
I deployed the pi application based on pi.yaml when the mpiOpertor is running. 
The pi value in the pi-launcher is right and the information in MPIJob is correct.

**Comment by 0yukali0** [comment]
I forgot to describe the environment.
I adopts rancher desktop to simulate the k8s cluster.
My environment is:
The master node contains 2 cpu and  2G memory.
Kubernetes version is v1.23.10
Yunikorn version is v1.1.0

**Review by wilfred-s — APPROVED** [review]
LGTM, documentation change is logged and in progress
thank you @kannon92 for your first contribution!

**Pull request closed without merging**
