### PR TITLE
[YUNIKORN-2987] Remove -installsuffix switch during build

### PR DESCRIPTION
**Pull request by pbacsko**
### What is this PR for?
Remove the `-installsuffix` switch for `go build`. It used to be a workaround, but no longer needed.

### What type of PR is it?
* [ ] - Bug Fix
* [x] - Improvement
* [ ] - Feature
* [ ] - Documentation
* [ ] - Hot Fix
* [ ] - Refactoring

### Todos
* [ ] - Task

### What is the Jira issue?
https://issues.apache.org/jira/browse/YUNIKORN-2985

### Questions:
* [ ] - The licenses files need update.
* [ ] - There is breaking changes for older versions.
* [ ] - It needs documentation.

### CODE REVIEW

**Review by craigcondit — APPROVED** [review]
+1 LGTM, pending e2e tests.

**Review by wilfred-s — APPROVED** [review]
LGTM

**Comment by wilfred-s** [comment]
Do we need a similar PR for any of the other repos, like web to remove it there?

**Comment by pbacsko** [comment]
There's already one for the web: apache/yunikorn-web#226

**Pull request closed without merging**
