### PR TITLE
[YUNIKORN-1344] Set imagePullSecrets on placeholder pods if present

### PR DESCRIPTION
**Pull request by craigcondit**
### What is this PR for?
When a non-public placeholder image is used, secrets are not currently provided.

This patch uses the credentials supplied on the primary application pod to retrieve the placeholder image as well.

### What type of PR is it?
* [x] - Bug Fix
* [ ] - Improvement
* [ ] - Feature
* [ ] - Documentation
* [ ] - Hot Fix
* [ ] - Refactoring

### Todos
* [ ] - Task

### What is the Jira issue?
https://issues.apache.org/jira/browse/YUNIKORN-1344

### How should this be tested?
Updated existing unit tests. Also, manually verified that specifying a secret on a pod with a task group also creates it on the associated placeholders.

### Questions:
* [ ] - The licenses files need update.
* [ ] - There is breaking changes for older versions.
* [ ] - It needs documentation.

### CODE REVIEW

**Review by wilfred-s — CHANGES_REQUESTED** [review]
The code changes look good.
What I am missing is a test for the `getAppMetadata()` call. Can we please add that test? We already have a number of them in `metadata_test.TestGetAppMetadata()` adding the secrets in a test should help increase the coverage.

**Comment by pbacsko** [comment]
With the extra unit tests, LGTM +1 from me (pending)

**Review by pbacsko — APPROVED** [review]
+1 (pending unit tests)

**Comment by craigcondit** [comment]
> The code changes look good. What I am missing is a test for the `getAppMetadata()` call. Can we please add that test? We already have a number of them in `metadata_test.TestGetAppMetadata()` adding the secrets in a test should help increase the coverage.

Test added.

**Pull request closed without merging**
