### PR TITLE
[YUNIKORN-1266] Add some examples related to app placement rules

### PR DESCRIPTION
**Pull request by 0yukali0**
### What is this PR for?
The placements page describes the types  and some cases but there're not relevant examples in deployment repository.
This commit adds some examples according to the [rules introduction](https://yunikorn.apache.org/docs/user_guide/placement_rules#rules)

### What type of PR is it?
* [ ] - Bug Fix
* [x] - Improvement
* [ ] - Feature
* [ ] - Documentation
* [ ] - Hot Fix
* [ ] - Refactoring

### Todos
* [ ] - Task

### What is the Jira issue?
https://issues.apache.org/jira/browse/YUNIKORN-1266

### How should this be tested?
1. Deploy these yaml files and the configuration is changed according to the different example.
2. The log message  in yunikorn-scheduler-k8s container  is showed by `kubectl logs` command 

### Questions:
* [ ] - The licenses files need update.
* [ ] - There is breaking changes for older versions.
* [ ] - It needs documentation.

### CODE REVIEW

**Review by wilfred-s — CHANGES_REQUESTED** [review]
build failed: yaml files need a license header, please fix
Instead of providing just a pod yaml I would expect two files. A queue configuration that needs to be added to the values.yaml and a pod definition. A README should explain how to use that queue configuration the pod or queue file should explain the expected behaviour (what is used and what is ignored etc).

The example for provided also seems incorrect.

**Comment by 0yukali0** [comment]
@wilfred-s Understood.

**Comment by 0yukali0** [comment]
Hi @wilfred-s, should I added some tests to the dispatcher and how do I know which test i could improve?

**Review by wilfred-s — CHANGES_REQUESTED** [review]
one last nit: please make sure all files have a newline at the end of the file. The git diff viewer shows that it is missing in some of the files.

**Comment by 0yukali0** [comment]
Understood.

**Pull request closed without merging**
