### PR TITLE
[YUNIKORN-2222] Remove unused state

### PR DESCRIPTION
**Pull request by targetoee**
### What is this PR for?
The QuatoApproved state has been removed in the previous issue. There was an omission, so this PR removes that.

### What type of PR is it?
* [x] - Bug Fix
* [ ] - Improvement
* [ ] - Feature
* [ ] - Documentation
* [ ] - Hot Fix
* [ ] - Refactoring

### Todos
N/A

### What is the Jira issue?
[YUNIKORN-2222](https://issues.apache.org/jira/browse/YUNIKORN-2222/)

### How should this be tested?
Unit test and e2e test.

### Screenshots (if appropriate)
N/A

### Questions:
N/A

### CODE REVIEW

**Review by chia7712 — APPROVED** [review]
LGTM

@targetoee Could you update doc also? https://yunikorn.apache.org/docs/design/scheduler_plugin/#shim-scheduler-changes

**Review by wilfred-s — APPROVED** [review]
LGTM

**Comment by targetoee** [comment]
Thanks for the review. I create a follow up issue in [YUNIKORN-2243](https://issues.apache.org/jira/browse/YUNIKORN-2243) to update the document.

**Comment by chia7712** [comment]
The failed e2e is traced by https://issues.apache.org/jira/browse/YUNIKORN-2244

**Pull request merged**
