### PR TITLE
[YUNIKORN-2910] Fix data corruption due to insufficient shim context locking

### PR DESCRIPTION
**Pull request by craigcondit**
### What is this PR for?
Restore context locking that was removed as part of YUNIKORN-2629. The locks are necessary to prevent logical data corruption due to concurrent processing of both pod and node events.

### What type of PR is it?
* [x] - Bug Fix
* [ ] - Improvement
* [ ] - Feature
* [ ] - Documentation
* [ ] - Hot Fix
* [ ] - Refactoring

### Todos
* [ ] - Task

### What is the Jira issue?
https://issues.apache.org/jira/browse/YUNIKORN-2910

### How should this be tested?
Ensure existing tests still pass and new deadlocks are not introduced. 

### Questions:
* [ ] - The licenses files need update.
* [ ] - There is breaking changes for older versions.
* [ ] - It needs documentation.

### CODE REVIEW

**Review by zhuqi-lucas — COMMENTED** [review]
Do we have a good way to mock or reproduce those data race/corruption issues?

It will be very helpful if we can do it easily, for both e2e testing or unit test.

**Review by pbacsko — APPROVED** [review]
+1

**Comment by pbacsko** [comment]
> Do we have a good way to mock or reproduce those data race/corruption issues?
> 
> It will be very helpful if we can do it easily, for both e2e testing or unit test.

**Comment by zhuqi-lucas** [comment]
> > Do we have a good way to mock or reproduce those data race/corruption issues?
> > It will be very helpful if we can do it easily, for both e2e testing or unit test.
> 
> I don't think so. It's very difficult to repro things like that. Sometimes it's totally workload dependent.

Ok, i see.

**Comment by shravan-achar** [comment]
I am working on making issues more reproducible. Will share updates more widely.

**Pull request closed without merging**
