### PR TITLE
[YUNIKORN-2557]Update the doc for e2e-tests

### PR DESCRIPTION
**Pull request by SophieTech88**
YUNIKORN-2557

### What is this PR for?
When I want to run the e2e-tests for the first time, it is a time consuming process to install the tools one by one, then learn from the failure to figure out I need to link the path of each tool to the tools/ folder as pre-requisite step. And there is an easy way to run the command `make tools` to set up everything we need before we run the e2e-tests.

So it is great to update the doc for e2e-tests to set up the environment in an easy way.

### What type of PR is it?
* [ ] - Bug Fix
* [x] - Improvement
* [ ] - Feature
* [ ] - Documentation
* [ ] - Hot Fix
* [ ] - Refactoring

### Todos
* [ ] - Task

### What is the Jira issue?
https://issues.apache.org/jira/browse/YUNIKORN-2557

### Questions:
* [ ] - The licenses files need update.
* [ ] - There is breaking changes for older versions.
* [ ] - It needs documentation.

### CODE REVIEW

**Comment by craigcondit** [comment]
The makefile should already have the e2e-tests target depend on the tools. If it doesn't that's the proper fix.

**Comment by chia7712** [comment]
> The makefile should already have the e2e-tests target depend on the tools. If it doesn't that's the proper fix.

The script skips the `make tools` if the tools folder is existent. That is a bit weird that we don't check all tools in the folder. Maybe the script should call `make tools` anyway, and let `make tools` do the check and install.

https://github.com/apache/yunikorn-k8shim/blob/bda57dda1a461517491d849bf8e3196ead3416a1/scripts/run-e2e-tests.sh#L74

**Comment by craigcondit** [comment]
Yes that should be made unconditional. It should only install the ones that are missing anyway.

**Comment by ryankert01** [comment]
+1 on removing the conditional. I've encountered this problem before.

**Comment by ryankert01** [comment]
> +1 on removing the conditional(or the `install_tools` function, and use `make tools`). I've encountered this problem before.

opened a jira regarding this:
https://issues.apache.org/jira/browse/YUNIKORN-2558

**Comment by chia7712** [comment]
#819 gets merged so I'm going to close this PR.

**Pull request closed without merging**
