### PR TITLE
[YUNIKORN-2653] Gang scheduling K8s event formatting compliance

### PR DESCRIPTION
**Pull request by wilfred-s**
### What is this PR for?
The K8s events provide definitions and rules around the content of the fields within the event. Adjust the content of gang scheduling related events to comply with the rules.
Only affects the Reason and Action fields in the events.

### What type of PR is it?
* [X] - Improvement

### What is the Jira issue?
* [YUNIKORN-2653](https://issues.apache.org/jira/browse/YUNIKORN-2653)

### How should this be tested?
N/A: event content change only

### CODE REVIEW

**Review by pbacsko — APPROVED** [review]
+1 changes are straightforward

**Review by manirajv06 — CHANGES_REQUESTED** [review]
Can you also take care of task.go?

**Review by pbacsko — CHANGES_REQUESTED** [review]
Need a small change in `ąpplication_test.go`

```
@@ -1196,7 +1196,7 @@ func TestPlaceholderTimeoutEvents(t *testing.T) {
        // after handle release event the states of app must be running
        assertAppState(t, app, ApplicationStates().Running, 3*time.Second)
 
-       message := "Placeholder timed out"
+       message := "GangScheduling"
        reason := "placeholder has been timed out"
        // check that the event has been published
        err = utils.WaitForCondition(func() bool {
```

We could temporarily disable the failing unit test and re-enable as soon as we have a satisfactory solution for the locking.

**Comment by wilfred-s** [comment]
fixed the text in the test

**Review by pbacsko — APPROVED** [review]
+1

**Pull request closed without merging**
