### PR TITLE
[YUNIKORN-2782] Cleanup dead code in cache/context

### PR DESCRIPTION
**Pull request by blueBlue0102**
### What is this PR for?
Cleanup dead code in cache/context

### What type of PR is it?
* [x] - Refactoring

### What is the Jira issue?
[YUNIKORN-2782](https://issues.apache.org/jira/projects/YUNIKORN/issues/YUNIKORN-2782)

### How should this be tested?
pass unit test and e2e test

### CODE REVIEW

**Review by chenyulin0719 — APPROVED** [review]
+1 LGTM, I'm good with renaming 'RemoveApplicationInternal' to 'RemoveApplication'.

**Review by chia7712 — APPROVED** [review]
LGTM

**Comment by chia7712** [comment]
I will merge it tomorrow if no objections

**Review by ryankert01 — APPROVED** [review]
LGTM, good cleanup!

**Pull request closed without merging**
