### PR TITLE
[YUNIKORN-2715] Handle special characters for params like queue, user…

### PR DESCRIPTION
**Pull request by manirajv06**
…name & groupname

### What is this PR for?

QueueName, UserName and GroupName may contain special characters which need to be escaped before hitting the url. Added the tests to verify this behaviour.

### What type of PR is it?
* [ ] - Improvement

### Todos
* [ ] - Task

### What is the Jira issue?
https://issues.apache.org/jira/browse/YUNIKORN-2715

### Questions:
* [ ] - The licenses files need update.
* [ ] - There is breaking changes for older versions.
* [ ] - It needs documentation.

### CODE REVIEW

**Comment by manirajv06** [comment]
@pbacsko Can you take a look? E2E test failure is not related to this pr.

**Comment by pbacsko** [comment]
@manirajv06 could you temporarily disable the failing tests until the problem is resolved? We've been having failed builds for a good week now. Just like I did with [YUNIKORN-2668](https://issues.apache.org/jira/browse/YUNIKORN-2668)

**Comment by manirajv06** [comment]
@pbacsko can you take a look?

**Review by pbacsko — APPROVED** [review]
+1

**Review by chia7712 — APPROVED** [review]
LGTM

**Pull request closed without merging**
