### PR TITLE
[YUNIKORN-1580] Upgrade github.com/looplab/fsm to stable version

### PR DESCRIPTION
**Pull request by 0yukali0**
### What is this PR for?
Upgrading [github.com/looplab/fsm](https://github.com/looplab/fsm) from v0.1.0 to v1.0.1. 
Related fsm documetations: [fsm in go package](https://pkg.go.dev/github.com/looplab/fsm@v1.0.1#section-readme) and [fsm github](https://github.com/looplab/fsm) .
The difference between v0.1.0 and v1.0.1 is following:
1. parameters of callback function are different. [v0.1.0 def](https://github.com/looplab/fsm/blob/v0.1.0/fsm.go#L82) v.s. [v1.0.1](https://github.com/looplab/fsm/blob/v1.0.1/fsm.go#L87)
2. parameters of fsm.Event are different. [v0.1.0 def](https://github.com/looplab/fsm/blob/v1.0.1/fsm.go#L296) v.s. [v1.0.1](https://github.com/looplab/fsm/blob/v0.1.0/fsm.go#L269)

### What type of PR is it?
* [ ] - Bug Fix
* [ ] - Improvement
* [ ] - Feature
* [ ] - Documentation
* [ ] - Hot Fix
* [ ] - Refactoring
* [x] - Task

### What is the Jira issue?
https://issues.apache.org/jira/browse/YUNIKORN-1580

### How should this be tested?
If the YUNIKORN-1580 in core side is not be merged, you need to clone the YUNIKORN-1580 in core.
1. modifying the `go.mod` require and redirect the core dependency to local core rep.
2. `make test`
If the YUNIKORN-1580 in core side is merged, only one thing is to try the command `make test`

### Questions:
* [ ] - The licenses files need update.
* [ ] - There is breaking changes for older versions.
* [ ] - It needs documentation.

### CODE REVIEW

**Comment by 0yukali0** [comment]
Expected failure is because the [modification](https://github.com/apache/yunikorn-core/pull/508) in core side is not merged.

**Comment by 0yukali0** [comment]
YUNIKOR-1580 in core side was merged and the fsm version problem in core side does not exist.
I restart the Pre-commit check and the unit test step will pass.

**Comment by 0yukali0** [comment]
Hi @wilfred-s , how do change the core version to the  latest version of core?
I successfully ran the UT in k8shim with the latest core which I cloned from the apache/yunikorn-core:master.
image

**Comment by 0yukali0** [comment]
Updating the package dependency.
Core version is latest.

**Review by wilfred-s — APPROVED** [review]
LGTM

**Pull request closed without merging**
