### PR TITLE
[YUNIKORN-2330] [e2e] Some test suites do not upload test artifacts

### PR DESCRIPTION
**Pull request by pbacsko**
### What is this PR for?
Fix e2e test suites which do not upload test artifacts after YUNIKORN-2305.

### What type of PR is it?
* [x] - Bug Fix
* [ ] - Improvement
* [ ] - Feature
* [ ] - Documentation
* [ ] - Hot Fix
* [ ] - Refactoring

### Todos
* [ ] - Task

### What is the Jira issue?
https://issues.apache.org/jira/browse/YUNIKORN-2330

### Questions:
* [ ] - The licenses files need update.
* [ ] - There is breaking changes for older versions.
* [ ] - It needs documentation.

### CODE REVIEW

**Comment by chia7712** [comment]
@chenyulin0719 could you take a look?

**Review by chenyulin0719 — APPROVED** [review]
LGTM, it was missing in YUNIKORN-2305.

**Comment by chenyulin0719** [comment]
Checked the failed e2e test is the same issue of [[YUNIKORN-2313] Flaky E2E Test: "Verify_basic_preemption" try to request more resource than the node’s available resource
](https://issues.apache.org/jira/browse/YUNIKORN-2313)

**Review by craigcondit — APPROVED** [review]
+1 LGTM.

**Pull request closed without merging**
