### PR TITLE
[YUNIKORN-2282] Missing function Stop() in shim SchedulerAPI mock classes

### PR DESCRIPTION
**Pull request by chenyulin0719**
### What is this PR for?
- Add Stop() method to Shim's SchedulerAPI mock classes
- Update yunikorn-core/yunikorn-scheduler-interface to latest in go.mod

### What type of PR is it?
* [x] - Bug Fix
* [ ] - Improvement
* [ ] - Feature
* [ ] - Documentation
* [ ] - Hot Fix
* [ ] - Refactoring

### Todos
NA

### What is the Jira issue?
https://issues.apache.org/jira/browse/YUNIKORN-2282

### Screenshots (if appropriate)
NA

### Questions:
NA

### CODE REVIEW

**Comment by craigcondit** [comment]
This is already included in #734 which is a much larger refactor that would require a rebase if this PR is merged. Closing for now.

**Comment by chia7712** [comment]
@chenyulin0719  Could you revise the PR to reduce the conflicts?

**Comment by craigcondit** [comment]
I'll deal with the conflicts in #734.

**Review by chia7712 — APPROVED** [review]
LGTM

@craigcondit I will merge it tomorrow if you have no more comments. thanks !

**Comment by chenyulin0719** [comment]
Many thanks for the help form @chia7712, @craigcondit. :)

**Pull request closed without merging**
