### PR TITLE
[YUNIKORN-2170] e2e test setup takes a lot of time

### PR DESCRIPTION
**Pull request by brandboat**
### What is this PR for?
Apply github actions cache to store e2e required tools.

### What type of PR is it?
* [x] - Improvement

### Todos
N/A

### What is the Jira issue?
https://issues.apache.org/jira/browse/YUNIKORN-2170

### How should this be tested?
noncache https://github.com/brandboat/yunikorn-k8shim/actions/runs/6959015015/job/18935536417
cached https://github.com/brandboat/yunikorn-k8shim/actions/runs/6960059624

### Questions:
N/A

### CODE REVIEW

**Comment by pbacsko** [comment]
@brandboat thanks for the PR, will you update it with the `spark-3.3.3-bin-hadoop3.tgz` binary?

**Comment by brandboat** [comment]
> @brandboat thanks for the PR, will you update it with the spark-3.3.3-bin-hadoop3.tgz binary?

Sure, will rebase to the latest commit in master

**Comment by pbacsko** [comment]
@brandboat will you update the PR to include the Spark caching?

**Comment by brandboat** [comment]
> @brandboat will you update the PR to include the Spark caching?

This pr cache the whole tools directory, so yes the Spark caching is already cached.

**Comment by pbacsko** [comment]
Ah cool.

**Review by pbacsko — APPROVED** [review]
+1 LGTM

**Pull request closed without merging**
