### PR TITLE
[YUNIKORN-1676] E2E: Spark test times out

### PR DESCRIPTION
**Pull request by zhuqi-lucas**
### What is this PR for?
Change the spark kill way to the  stable kill all pod way.

### What type of PR is it?
* [x] - Bug Fix
* [x] - Improvement
* [ ] - Feature
* [ ] - Documentation
* [ ] - Hot Fix
* [ ] - Refactoring

### Todos
* [ ] - Task

### What is the Jira issue?
* Open an issue on Jira https://issues.apache.org/jira/browse/YUNIKORN/
* Put link here, and add [YUNIKORN-*Jira number*] in PR title, eg. `[YUNIKORN-2] Gang scheduling interface parameters`

### Questions:
* [ ] - The licenses files need update.
* [ ] - There is breaking changes for older versions.
* [ ] - It needs documentation.

### CODE REVIEW

**Review by craigcondit — CHANGES_REQUESTED** [review]
-1. This isn't really a timeout issue, it's a flaky test. The problem seems to be that the "kill spark jobs" step is unreliable. This should take seconds, not minutes. Need to determine why that is failing and fix the underlying issue.

**Comment by zhuqi-lucas** [comment]
Thank you @craigcondit for review,
I also think increse timeout is not a good idea, but it seems hard for us to find the root flaky case.

**Comment by zhuqi-lucas** [comment]
@craigcondit 
Change spark jobs kill to a stable way to delete pod one by one in latest PR.

**Review by craigcondit — APPROVED** [review]
+1 LGTM.

**Pull request closed without merging**
