### PR TITLE
[YUNIKORN-1597] e2e tests: Recover assigned pods in Bound state

### PR DESCRIPTION
**Pull request by pbacsko**
### What is this PR for?
The PR contains an e2e test which validates that YK can recover properly with Running/Pending placeholders.

### What type of PR is it?
* [ ] - Bug Fix
* [x] - Improvement
* [ ] - Feature
* [ ] - Documentation
* [ ] - Hot Fix
* [ ] - Refactoring

### Todos
* [ ] - Task

### What is the Jira issue?
https://issues.apache.org/jira/browse/YUNIKORN-1597

### Questions:
* [ ] - The licenses files need update.
* [ ] - There is breaking changes for older versions.
* [ ] - It needs documentation.

### CODE REVIEW

**Comment by craigcondit** [comment]
I don't think we want to add the taints/tolerations to helm or refer to kind directly, as these tests are meant to be runnable on all types of clusters (not just kind). Can we eliminate this?

**Comment by craigcondit** [comment]
Alternate approach: Query the cluster for nodes with available capacity, and construct nodes with nodeAffinity specified so that they are only schedulable on those nodes.

**Comment by pbacsko** [comment]
> I'm -1 on this approach as it doesn't allow for running on anything but a Kind cluster. Our tests should be cluster-agnostic, and adapt to the environment they are run in so that they can be used on real clusters as well.
Yeah, most tests are agnostic, but there are some (maybe just the one which I modified) which already depends on having 3 nodes (1 control + 2 worker). Perhaps the existing tests should be fixed, too in a follow-up JIRA.

> Alternate approach: Query the cluster for nodes with available capacity, and construct pods with nodeAffinity specified so that they are only schedulable on those nodes.
Hm, interesting. I'll try this.

**Comment by pbacsko** [comment]
Test failure seems to be unrelated.

**Comment by manirajv06** [comment]
@pbacsko [PR](https://github.com/apache/yunikorn-k8shim/commit/817042e2e4b3e79b222f34132795f80ecc1e22ef) has introduced new methods to set/remove node labels etc. There was a need to add taint/untaint node methods as well to remove the dependency on k8s test framework. Hence used some methods from this PR to above said PR. So, Please rebase your wc and take it forward.

**Review by craigcondit — APPROVED** [review]
+1 LGTM.

**Pull request closed without merging**
