### PR TITLE
[YUNIKORN-1806] Add configuration entries for YuniKorn Application Tracking

### PR DESCRIPTION
**Pull request by mitdesai**
### What is this PR for?
A few sentences describing the overall goals of the pull request's commits.
First time? Check out the contributing guide - http://yunikorn.apache.org/community/how_to_contribute   

### What type of PR is it?
* [ ] - Bug Fix
* [X] - Improvement
* [ ] - Feature
* [ ] - Documentation
* [ ] - Hot Fix
* [ ] - Refactoring

### Todos
* [ ] - Task

### What is the Jira issue?
* Open an issue on Jira https://issues.apache.org/jira/browse/YUNIKORN/1806

### Questions:
* [ ] - The licenses files need update.
* [ ] - There is breaking changes for older versions.
* [X] - It needs documentation.

### CODE REVIEW

**Comment by craigcondit** [comment]
There seem to be several unrelated changes included with this PR. Additionally, it would make more sense for this to go in the core as that's where the functionality for event tracking will be implemented.

Finally, we should attempt to make these configuration options hot-reloadable. This shouldn't be too difficult as most of them simply either turn the feature on or off, or set the max size. Setting the max size will require copying the existing queue to a new one of a different size, but that's all.

**Comment by pbacsko** [comment]
Yes, these settings should be defined in the core inside `queue.yaml`.

**Comment by craigcondit** [comment]
Not in queues.yaml. These are system-wide settings and have nothing to do with the scheduler queues.

**Comment by mitdesai** [comment]
> Not in queues.yaml. These are system-wide settings and have nothing to do with the scheduler queues. 

Yes. Let me fix this. I have got some more clarity on this one after I spoke with Wilfred yesterday.

**Comment by mitdesai** [comment]
Additional changes are mainly adding test coverage and fixing some issues pointed by linter.

I will update and create another PR in core.

**Pull request closed without merging**
