### PR TITLE
[YUNIKORN-2760] `make tools` should check the version of tools

### PR DESCRIPTION
**Pull request by blueBlue0102**
### What is this PR for?
Makefile, by default, checks only the existence of file. Hence, developers need to remove tools folder (or call `make distclean`) manually to trigger the installation after we update the version of tools.

However, how developers can be aware of the tools updates? Personally, I smell fishy from the error of warning, but that could be implicit and noisy :cry

In order to fix that, I'd like to introduce the new folder structure to tools folder: 

```
/tools/{tool_name}-{version}
```

That offers a unique path to each version of tool. Developers will not miss the updates anymore.

### What type of PR is it?
* [x] - Improvement

### What is the Jira issue?
[YUNIKORN-2760](https://issues.apache.org/jira/projects/YUNIKORN/issues/YUNIKORN-2760)

### How should this be tested?

Currently, `make tools` is triggered only by `./scripts/run-e2e-tests.sh`
To verify whether `make tools` checks the tools' versions, call any command in `./scripts/run-e2e-tests.sh` or trigger it manually

### Screenshots (if appropriate)

image

### CODE REVIEW

**Comment by pbacsko** [comment]
@blueBlue0102 please check the e2e test output, something is wrong with the "ginkgo" command, I suppose it is related to your change.

**Comment by blueBlue0102** [comment]
@pbacsko The problem has been solved, and the e2e test has passed on my [forked repo](https://github.com/blueBlue0102/yunikorn-k8shim/actions/runs/10123252877). Please let me know if there are any further issues. Thank you!

**Review by pbacsko — APPROVED** [review]
+1 LGTM

**Review by craigcondit — APPROVED** [review]
+1 LGTM

**Comment by chia7712** [comment]
@blueBlue0102 thanks for this great improvement!

**Pull request closed without merging**
