### PR TITLE
[YUNIKORN-1389] Pass node labels from shim to core

### PR DESCRIPTION
**Pull request by zhuqi-lucas**
### What is this PR for?
Suggested by [YUNIKORN-1362](https://issues.apache.org/jira/browse/YUNIKORN-1362):
The YuniKorn UI shows the list of all the nodes in the cluster. There is no way of filtering the list.

We have only certain nodes that we want our jobs to be scheduled in the cluster and that is dictated by the nodeSelector. I would good to have a way to show only those nodes on the UI to give a better idea of the resources that we have for the jobs to be scheduled 

The functionality will depend on the details we pull for the nodes into the core. Propagating some info for a node from the shim into the core might be needed.

Here we first to pass node labels from shim to core.

### What type of PR is it?
* [ ] - Bug Fix
* [x] - Improvement
* [ ] - Feature
* [ ] - Documentation
* [ ] - Hot Fix
* [ ] - Refactoring

### Todos
* [ ] - Task

### What is the Jira issue?
* Open an issue on Jira https://issues.apache.org/jira/browse/YUNIKORN-1389
* Put link here, and add [YUNIKORN-*Jira number*] in PR title, eg. `[YUNIKORN-2] Gang scheduling interface parameters`

### Questions:
* [ ] - The licenses files need update.
* [ ] - There is breaking changes for older versions.
* [ ] - It needs documentation.

### CODE REVIEW

**Comment by pbacsko** [comment]
@zhuqi-lucas please rebase this change, thx

**Comment by zhuqi-lucas** [comment]
Thank you, @pbacsko, for reminder, rebased now.

**Review by 0yukali0 — APPROVED** [review]
LGTM

**Review by craigcondit — APPROVED** [review]
+1 will merge shortly.

**Pull request closed without merging**
