### PR TITLE
[YUNIKORN-1404] e2e: don't delete individual pods when jobs are submitted

### PR DESCRIPTION
**Pull request by pbacsko**
### What is this PR for?
Don't just clean up individual pods when jobs are submitted, instead, delete the job then delete any pods in the namespace which are still there. This ensure proper cleanup.

### What type of PR is it?
* [ ] - Bug Fix
* [x] - Improvement
* [ ] - Feature
* [ ] - Documentation
* [ ] - Hot Fix
* [ ] - Refactoring

### Todos
* [ ] - Task

### What is the Jira issue?
https://issues.apache.org/jira/browse/YUNIKORN-1404

### Questions:
* [ ] - The licenses files need update.
* [ ] - There is breaking changes for older versions.
* [ ] - It needs documentation.

### CODE REVIEW

**Comment by manirajv06** [comment]
@pbacsko Changes looks good. Are you planning to add any more changes? If not, Can you check the test failures and take this forward?

**Comment by pbacsko** [comment]
Update: new PR contains some refactor & simplifications.

**Comment by pbacsko** [comment]
@manirajv06 fixed all issues, pls review

**Review by craigcondit — APPROVED** [review]
+1 LGTM.

**Pull request closed without merging**
