### PR TITLE
[YUNIKORN-1957] Add e2e tests for user and group limits with wildcard

### PR DESCRIPTION
**Pull request by rrajesh-cloudera**
This PR introduces user and group limit test enhancements in the `user_group_limit_test.go` file. It adds new test cases to verify the behavior of the scheduler when user and group limits are set and updated. The tests cover scenarios where the user and group limits are exceeded, not defined, and changed. The PR also includes tests for wildcard users and group limits. These enhancements ensure that the scheduler correctly handles user and group limits in various scenarios.

### What type of PR is it?
* [ ] - Bug Fix
* [ ] - Improvement
* [ ] - Feature
* [ ] - Documentation
* [ ] - Hot Fix
* [ ] - Refactoring

### Todos
* [ ] - Task

### What is the Jira issue?
https://issues.apache.org/jira/browse/YUNIKORN-1957

### Questions:
* [ ] - The licenses files need update.
* [ ] - There is breaking changes for older versions.
* [ ] - It needs documentation.

### CODE REVIEW

**Review by pbacsko — CHANGES_REQUESTED** [review]
Please fix the linter problems. You can check locally by running "make lint".

**Comment by rrajesh-cloudera** [comment]
> Please fix the linter problems. You can check locally by running "make lint".

Hi @pbacsko , Fixed the Linter.

**Review by pbacsko — APPROVED** [review]
LGTM

**Review by craigcondit — APPROVED** [review]
+1 LGTM. Rebased on master to fix merge conflicts.

**Pull request closed without merging**
