### PR TITLE
[YUNIKORN-1867] add priority offset e2e test

### PR DESCRIPTION
**Pull request by FrankYang0529**
### What is this PR for?

Add `priority.offset` property e2e test.

### What type of PR is it?
* [ ] - Bug Fix
* [X] - Improvement
* [ ] - Feature
* [ ] - Documentation
* [ ] - Hot Fix
* [ ] - Refactoring

### Todos
* [ ] - Task

### What is the Jira issue?

https://issues.apache.org/jira/browse/YUNIKORN-1867

### Questions:
* [ ] - The licenses files need update.
* [ ] - There is breaking changes for older versions.
* [ ] - It needs documentation.

### CODE REVIEW

**Review by craigcondit — CHANGES_REQUESTED** [review]
Seeing quite a few test failures on this, need to investigate and fix.

**Comment by FrankYang0529** [comment]
> Seeing quite a few test failures on this, need to investigate and fix.

The root cause of error test cases is that we can't add child queue to a draining queue. In the first case, we add three queues `root.fence`, `root.fence.child1`, and `root.fence.child2`. After we reset the configuration, these three queues will get into the draining state. Then, another case tries to add child queues to `root.fence` and the case gets error.

Currently, the yunikorn-core will clean draining queues every 10 seconds. The duration is hardcoded in the source code. Users can't update it. Do we want to add the setting to the configuration? If yes, I can help to add it.

CI failed job: https://github.com/apache/yunikorn-k8shim/actions/runs/5575867672/jobs/10202470269
Cleaning draining queues source code: https://github.com/apache/yunikorn-core/blob/129c0de6b12b21b4282631b2c0b6df188ce7ae80/pkg/scheduler/partition_manager.go#L70-L87

**Review by wilfred-s — APPROVED** [review]
LGTM
Change looked more complicated due to diff layout

**Review by craigcondit — APPROVED** [review]
+1 LGTM.

**Pull request closed without merging**
