### PR TITLE
[YUNIKORN-2393] Upgrade codecov/codecov-action to v4

### PR DESCRIPTION
**Pull request by chenyulin0719**
### What is this PR for?
Upgrade codecov/codecov-action from v3 to v4.
Support "secrets.CODECOV_TOKEN" for codecov analysis in forked repo.

### What type of PR is it?
* [ ] - Bug Fix
* [x] - Improvement
* [ ] - Feature
* [ ] - Documentation
* [ ] - Hot Fix
* [ ] - Refactoring

### Todos
NA

### What is the Jira issue?
https://issues.apache.org/jira/browse/YUNIKORN-2393

### How should this be tested?
Trigger workflow then check codecov report in PR conversation.

### Screenshots (if appropriate)
NA

### Questions:
NA

### CODE REVIEW

**Comment by chia7712** [comment]
@chenyulin0719 Does it look good at your repo?

**Comment by chenyulin0719** [comment]
@chia7712 ,
Yes, it looks good in my repo.
- https://github.com/chenyulin0719/yunikorn-k8shim/pull/34#issuecomment-1932256160

**Comment by chia7712** [comment]
will merge it after QA

**Review by wilfred-s — APPROVED** [review]
LGTM

**Pull request closed without merging**
